name: Check for broken links on site

on:
  workflow_run:
    workflows: [Build and deploy website]
    types: [completed]

permissions:
  contents: read

jobs:
  check-links-on-site:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'pull_request' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: ./.github/actions/setup-site
      - name: Build site
        run: bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production
      - name: Check local links
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          fail: true
          args: --offline --remap '_site(/?.*)/assets/(.*) _site/assets/$2' --verbose --no-progress '_site/**/*.html'
